name: Check Syntax

on:
  push:
    branches:
      - master

jobs:
  syntax-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          jdk: '17'

      - name: Build with Maven
        run: mvn clean compile -DskipTests=true

      - name: Run Checkstyle
        run: mvn checkstyle:check

      - name: Upload Checkstyle Results
        uses: actions/upload-artifact@v2
        with:
          name: checkstyle-results
          path: target/checkstyle-result.xml